name: Allow only C files

on:
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check file extensions
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }})

          for file in $files; do
            if [[ ! "$file" =~ \.(c|h)$ ]]; then
              echo "❌ Non-C file detected: $file"
              exit 1
            fi
          done

          echo "✅ Only C files detected"
